schedule_seed = [
    {
        "year": 2025,
        "month": "Май",
        "project": "Life Town",
        "revision_info": "Первая ревизия",
        "event_date": "2025-05-14",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 117630.0,
        "amount_actual": 117630.0,
    },
    {
        "year": 2025,
        "month": "Июль",
        "project": "City+",
        "revision_info": "Первая ревизия",
        "event_date": "2025-07-12",
        "weekday": "Четверг",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 422922.0,
        "amount_actual": 422922.0,
    },
    {
        "year": 2025,
        "month": "Август",
        "project": "Life Town",
        "revision_info": "Первая ревизия",
        "event_date": "2025-08-11",
        "weekday": "Понедельник",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 159506.0,
        "amount_actual": 159506.0,
    },
    {
        "year": 2025,
        "month": "Август",
        "project": "Hayat",
        "revision_info": "Первая ревизия",
        "event_date": "2025-08-20",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 802416.0,
        "amount_actual": 802416.0,
    },
    {
        "year": 2025,
        "month": "Октябрь",
        "project": "Big Vill",
        "revision_info": "Первая ревизия",
        "event_date": "2025-10-22",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 698842.0,
        "amount_actual": 698842.0,
    },
    {
        "year": 2025,
        "month": "Ноябрь",
        "project": "City+",
        "revision_info": "Первая ревизия",
        "event_date": "2025-11-12",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 499813.0,
        "amount_actual": 499813.0,
    },
    {
        "year": 2025,
        "month": "Ноябрь",
        "project": "Life Town",
        "revision_info": "Первая ревизия",
        "event_date": "2025-11-05",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 302372.0,
        "amount_actual": 302372.0,
    },
    {
        "year": 2025,
        "month": "Ноябрь",
        "project": "Hayat",
        "revision_info": "Первая ревизия",
        "event_date": "2025-11-26",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 211886.0,
        "amount_actual": 211887.0,
    },
    {
        "year": 2026,
        "month": "Январь",
        "project": "ЖК 4U",
        "revision_info": "10/2/2025",
        "event_date": "2026-01-14",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 782248.0,
        "amount_actual": 777388.0,
    },
    {
        "year": 2026,
        "month": "Январь",
        "project": "Big Vill",
        "revision_info": "10/23/2025",
        "event_date": "2026-01-21",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 299044.0,
        "amount_actual": 299005.0,
    },
    {
        "year": 2026,
        "month": "Январь",
        "project": "Famous Town",
        "revision_info": "Первая ревизия",
        "event_date": "2026-01-28",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 446906.0,
        "amount_actual": 446906.0,
    },
    {
        "year": 2026,
        "month": "Февраль",
        "project": "Life Town",
        "revision_info": "11/5/2025",
        "event_date": "2026-02-04",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 185287.0,
        "amount_actual": 185284.0,
    },
    {
        "year": 2026,
        "month": "Февраль",
        "project": "City+",
        "revision_info": "11/12/2025",
        "event_date": "2026-02-11",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 87167.0,
        "amount_actual": 87165.0,
    },
    {
        "year": 2026,
        "month": "Февраль",
        "project": "Hayat",
        "revision_info": "11/26/2025",
        "event_date": "2026-02-25",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": 19478.0,
        "amount_actual": 19486.0,
    },
    {
        "year": 2026,
        "month": "Март",
        "project": "Rams",
        "revision_info": "Первая ревизия",
        "event_date": "2026-03-11",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Проведено",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Апрель",
        "project": "ЖК 4U",
        "revision_info": "1/14/2026",
        "event_date": "2026-04-15",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Не проведено",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Апрель",
        "project": "Big Vill",
        "revision_info": "1/21/2026",
        "event_date": "2026-04-21",
        "weekday": "Вторник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Апрель",
        "project": "ЖК Jetisy Park",
        "revision_info": "Первая ревизия",
        "event_date": "2026-04-23",
        "weekday": "Четверг",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Апрель",
        "project": "Asyltas",
        "revision_info": "1/28/2026",
        "event_date": "2026-04-28",
        "weekday": "Вторник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Апрель",
        "project": "Famous Town",
        "revision_info": "Первая ревизия",
        "event_date": "2026-04-30",
        "weekday": "Четверг",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Май",
        "project": "ЖК Forum Residence",
        "revision_info": "Первая ревизия",
        "event_date": "2026-05-04",
        "weekday": "Понедельник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Май",
        "project": "Комфорт Сити",
        "revision_info": "Первая ревизия",
        "event_date": "2026-05-05",
        "weekday": "Вторник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Май",
        "project": "ЖК Гульдер",
        "revision_info": "Первая ревизия",
        "event_date": "2026-05-06",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Май",
        "project": "ЖК Нурия",
        "revision_info": "Первая ревизия",
        "event_date": "2026-05-11",
        "weekday": "Понедельник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Май",
        "project": "Grand Vie",
        "revision_info": "Первая ревизия",
        "event_date": "2026-05-12",
        "weekday": "Вторник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Июнь",
        "project": "ЖК Arena City",
        "revision_info": "Первая ревизия",
        "event_date": "2026-06-01",
        "weekday": "Понедельник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Июнь",
        "project": "Назарбаева-Раимбека",
        "revision_info": "Первая ревизия",
        "event_date": "2026-06-02",
        "weekday": "Вторник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Июнь",
        "project": "Назарбаева-Раимбека",
        "revision_info": "Первая ревизия",
        "event_date": "2026-06-03",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Июнь",
        "project": "Qarasai Park",
        "revision_info": "Первая ревизия",
        "event_date": "2026-06-08",
        "weekday": "Понедельник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Июнь",
        "project": "Дом на Гагарина",
        "revision_info": "Первая ревизия",
        "event_date": "2026-06-09",
        "weekday": "Вторник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Июнь",
        "project": "Izumrud Residence",
        "revision_info": "Первая ревизия",
        "event_date": "2026-06-10",
        "weekday": "Среда",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Июнь",
        "project": "Navoi 3.0",
        "revision_info": "Первая ревизия",
        "event_date": "2026-06-11",
        "weekday": "Четверг",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
    {
        "year": 2026,
        "month": "Июнь",
        "project": "ЖК New Life",
        "revision_info": "Первая ревизия",
        "event_date": "2026-06-15",
        "weekday": "Понедельник",
        "inspection_type": "Комплексная",
        "status": "Запланировано",
        "amount_planned": None,
        "amount_actual": None,
    },
]